name: Check Aufgabe_3

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Install dotnet 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
    - name: Compile file
      run: csc Aufgabe_3/Temperature.cs
